// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitleAttribute("Informedica.Utils.Lib")>]
[<assembly: AssemblyProductAttribute("Informedica.Utils.Lib")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate", "2021-01-19T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("1.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel", "release")>]
[<assembly: AssemblyMetadataAttribute("GitHash", "dc607d839abf2a6b7396899a112291aca38f608f")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "Informedica.Utils.Lib"

    [<Literal>]
    let AssemblyProduct = "Informedica.Utils.Lib"

    [<Literal>]
    let AssemblyVersion = "1.0.0"

    [<Literal>]
    let AssemblyMetadata_ReleaseDate = "2021-01-19T00:00:00.0000000+01:00"

    [<Literal>]
    let AssemblyFileVersion = "1.0.0"

    [<Literal>]
    let AssemblyInformationalVersion = "1.0.0"

    [<Literal>]
    let AssemblyMetadata_ReleaseChannel = "release"

    [<Literal>]
    let AssemblyMetadata_GitHash = "dc607d839abf2a6b7396899a112291aca38f608f"
