// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Informedica.Build.Template")>]
[<assembly: AssemblyProductAttribute("Informedica.Build")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-05-06T00:00:00.0000000+02:00")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("1.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","30be8c704f64b3e8bf3ad0c6e80b86817aa79ddd")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Informedica.Build.Template"
    let [<Literal>] AssemblyProduct = "Informedica.Build"
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-05-06T00:00:00.0000000+02:00"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
    let [<Literal>] AssemblyInformationalVersion = "1.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "30be8c704f64b3e8bf3ad0c6e80b86817aa79ddd"
