<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="./../Shared/Shared.fs" />
    <Compile Include="./../Shared/Api.fs" />
    <Compile Include="Extensions.fs" />
    <Compile Include="Utils.fs" />
    <Compile Include="Bindings.fs" />
    <Compile Include="Mui.fs" />
    <Compile Include="./Components/Markdown.fs" />
    <Compile Include="./Components/DropDownBox.fs" />
    <Compile Include="./Components/AccordionList.fs" />
    <Compile Include="./Components/SelectableList.fs" />
    <Compile Include="./Components/TitleBar.fs" />
    <Compile Include="./Components/NavigationBar.fs" />
    <Compile Include="./Components/ReportMenu.fs" />
    <Compile Include="./Components/ColoredList.fs" />
    <Compile Include="./Components/PieChart.fs" />
    <Compile Include="./Components/AdmissionGraph.fs" />
    <Compile Include="./Components/StackedBarChart.fs" />
    <Compile Include="./Components/MortalityGraph.fs" />
    <Compile Include="./Components/SMRGraph.fs" />
    <Compile Include="./Components/FunnelPlot.fs" />
    <Compile Include="./Components/OccupancyGraph.fs" />
    <Compile Include="./Pages/Report.fs" />
    <Compile Include="App.fs" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>