<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include=".\..\Shared\Shared.fs" />
    <Compile Include=".\..\Shared\Api.fs" />
    <Compile Include="Extensions.fs" />
    <Compile Include="Utils.fs" />
    <Compile Include="Bindings.fs" />
    <Compile Include="Mui.fs" />
    <Compile Include="Server.fs" />
    <Compile Include=".\Components\Types.fs" />
    <Compile Include=".\Components\Markdown.fs" />
    <Compile Include=".\Components\DropDownBox.fs" />
    <Compile Include=".\Components\Accordion.fs" />
    <Compile Include=".\Components\AccordionList.fs" />
    <Compile Include=".\Components\SelectableList.fs" />
    <Compile Include=".\Components\TitleBar.fs" />
    <Compile Include=".\Components\NavigationBar.fs" />
    <Compile Include=".\Components\ColoredList.fs" />
    <Compile Include=".\Components\PieChart.fs" />
    <Compile Include=".\Components\StackedBarChart.fs" />
    <Compile Include=".\Components\Dialog.fs" />
    <Compile Include=".\Components\TreeItem.fs" />
    <Compile Include=".\Components\SimpleTreeView.fs" />
    <Compile Include=".\Views\ReportMenu.fs" />
    <Compile Include=".\Views\DiagnosesMenu.fs" />
    <Compile Include=".\Views\AdmissionGraph.fs" />
    <Compile Include=".\Views\MortalityGraph.fs" />
    <Compile Include=".\Views\FunnelPlot.fs" />
    <Compile Include=".\Views\SMRGraph.fs" />
    <Compile Include=".\Views\OccupancyGraph.fs" />
    <Compile Include=".\Pages/Report.fs" />
    <Compile Include=".\Pages/Diagnoses.fs" />
    <Compile Include="App.fs" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>